### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by baseplate-admin** [dmptrluke/django-markdownfield#24]
Hi,

I want to know if this is maintained. As i plan to use this project in a production build of mine i would gladly be willing to help modernize this project

**Comment by benjaoming** [comment]
I was wondering the same -- @dmptrluke, I can offer to help get a few PRs in once in a while and publish new releases if you need :+1:

**Comment by bernd-wechner** [comment]
It seems not. The code was last touched Apr 11, 2021 and there's PR dating back to Jan 5, 2021 marked as "Should be merged". It's not unusual for FOSS to go stale if a maintainer gets distracted, and sees their priorities change. The reality of volunteer work. 

If I look at the Network graph:

https://github.com/dmptrluke/django-markdownfield/network

Alas, it looks like my own fork with a few fixes is the most up to date. But there are a few other contributions, commits by @Edrolo, @benjaoming, @kavdev, @zypro and @vgalaktionov that could/should perhaps all come together into master. 

Alas, unless @dmptrluke wakes up and invites someone else to manage PRs and such the project looks doomed to either remain stale or have another shining star open a django-markdownfield-ng or similar form, merging in these disparate community contribs and publishing to PyPi and maintaining that.

Alas, I lack the time for it (there's a fair startup cost just in rebranding and then cherry picking those community contribs and bringing them into the newly branded package and it would be much easier if @dmptrluke just added someone else or some other as collaborators with write permissions to the repo).  @benjaoming has already offered, but @dmptrluke  seems lost to other commitments and distractions at present.

**Comment by dmptrluke** [comment]
Hiya - I do intend to reply to them soon, I've just been distracted and it slipped my mind. I'll look at it later this week.

**Comment by dmptrluke** [comment]
I had an offer from @benjaoming to assist with maintenance a short while ago, so I've invited them to come on as a contributor to help maintain things.

**Comment by baseplate-admin** [comment]
Thanks..

**Comment by benjaoming** [comment]
Thanks @dmptrluke :wave: 

I have a couple of active projects using django-markdownfield, so it should come as a natural flow for me to check back every one in a while. Am also watching the repo activity :)

Have a great day!
