### ISSUE TITLE
Documentation needs to be clearer - very simple step missing

### ISSUE THREAD

**Issue by CarlMurray** [dmptrluke/django-markdownfield#28]
As a beginner it was definitely not obvious that I had to add "markdownfield" to my INSTALLED_APPS. I spent almost an hour banging my head against a wall until I finally decided to look for a different package - only when looking at docs for other packages did I realise that maybe I had to add it to my INSTALLED APPS. 

A single sentence on the package documentation page would save a lot of headache. Please add this step to the docs. It's not obvious for beginners.

**Comment by benjaoming** [comment]
Thanks for the feedback, please have a look at the PR and LMK if there are tweaks you'd like to add :+1:

**Comment by CarlMurray** [comment]
Whoops I just made a PR before I saw yours. Looks good though thanks for the quick response!

**Comment by benjaoming** [comment]
Ah okay, I read your issue description "Please add this step to the docs. It's not obvious for beginners" and thought you were definitely not gonna do it :smile:

**Comment by CarlMurray** [comment]
I wasn't going to, but then realise I could (I'm new to this stuff) 😄
