### ISSUE TITLE
Release 0.11

### ISSUE THREAD

**Issue by benjaoming** [dmptrluke/django-markdownfield#31]
I've been doing some PR merges. I'd like to run a manual test before releasing 0.11. But the changes have all looked non-breaking.

CC: @dmptrluke

**Comment by dmptrluke** [comment]
Looks good! I'll check over things myself as well, but I don't have a good test environment for this right now (new computer - I only have a live site to test on), so I would appreciate help confirming it all works.

I'm happy to push the release out whenever appropriate, if I recall you don't have access to pypi at this stage?

**Comment by benjaoming** [comment]
I'll be happy to sign off in this issue. You are welcome to invite my user on PyPi `benjaoming`, but I think I'm having 2FA issues because I was using a device that isn't supported anymore by my operating system :sob:

**Comment by dmptrluke** [comment]
I've done a few ancillary packaging changes to make sure we're showing as supporting the latest versions of Python. If you think things are ready to go I'll push a release to pypi.

**Comment by benjaoming** [comment]
I'll definitely ping you back as soon as I've done a test (was just visiting another project now) :+1: :balloon:

**Comment by benjaoming** [comment]
@dmptrluke after fixing #32, I think that this looks good. I tested that the field renders well and works in the admin :+1:

**Comment by dmptrluke** [comment]
I've tagged the current commit as v0.11.0 and pushed a new build out to pypi!

**Comment by benjaoming** [comment]
Nice! The new release worked for me :+1:
