### ISSUE TITLE
Multiline code doesn't work

### ISSUE THREAD

**Issue by kostja-me** [dmptrluke/django-markdownfield#7]
Hello!

First of all thanks for this awesome library.

I am really grateful for this work!

Now the problem:

Multiline code block with three backticks is represented as P tag with CODE tag inside. 
```html
<p>
    <code>print(f"Hello, {username}")</code>
</p>
```
This leads to ignored formatting, newlines, etc

Is it possible to make code blocks being wrapped in PRE tag?

```html
<pre>
    <code>alert();</code>
</pre>
```

Thank you, have a great day!

**Comment by kostja-me** [comment]
For those who will find this page, it requires the extension for markdown

https://github.com/Python-Markdown/markdown/issues/701#issuecomment-414127128

https://python-markdown.github.io/extensions/fenced_code_blocks/

**Comment by kostja-me** [comment]
Okay to solve this I added two lines into my settings.py.

```
MARKDOWN_EXTENSIONS = ['fenced_code']
MARKDOWN_EXTENSION_CONFIGS = {}

```


But I found a bug in the code of `django-markdownfield`.

in markdownfield/models.py this should be the correct line:

`EXTENSION_CONFIGS = getattr(settings, 'MARKDOWN_EXTENSION_CONFIGS', {})`

Configs are dict, not list.

**Comment by dmptrluke** [comment]
Thanks!

**Comment by dmptrluke** [comment]
I also decided to allow fenced code blocks by default, since they seem like an obvious choice, and I don't think the syntax will interfere with anything else (three backticks isn't something most people would use for anything else)
